name: mudawanat_aleibadat
description: "Track your daily deeds."

publish_to: "none"

version: 0.6.0+9

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  liquid_progress_indicator_v2: ^0.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  syncfusion_flutter_calendar: ^31.2.2
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab.ttf

flutter_intl:
  enabled: true
