name: mudawanat_aleibadat
description: "Track your daily deeds."

publish_to: "none"

version: 0.5.0+8

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lint: ^2.3.0
  liquid_progress_indicator_v2: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  syncfusion_flutter_calendar: ^26.1.41
  url_launcher: ^6.3.0
  window_manager: ^0.3.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab.ttf

flutter_intl:
  enabled: true
