name: mudawanat_alsala
description: "Track your daily deeds."

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  lint: ^2.3.0
  liquid_progress_indicator_v2: ^0.5.0
  path: ^1.8.3
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  syncfusion_flutter_calendar: ^24.2.3
  url_launcher: ^6.2.4
  window_manager: ^0.3.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true
