name: mudawanat_alsala
description: "Track your daily deeds."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  url_launcher: ^6.2.4
  sqflite: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  syncfusion_flutter_calendar: ^24.2.3
  lint: ^2.3.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true
